- name: Install basic build tools
  become: yes
  package:
    name:
      - build-essential
      - gcc
      - g++
      - cmake

- import_tasks: tasks/test_mock.yml
- import_tasks: tasks/benchmark.yml
