# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "peru/ubuntu-20.04-desktop-amd64"
  config.vm.box_version = "20200901.01"
  
  config.vagrant.plugins = ["vagrant-disksize"]
  config.disksize.size = '16GB'

  config.vm.network "private_network", type: "dhcp"

  config.ssh.forward_agent = true
  config.ssh.forward_x11 = true

  config.vm.provider "virtualbox" do |vb|
    vb.name = "prcpp-desktop"
    vb.memory = "4096"
    vb.cpus = 2
    vb.customize ["modifyvm", :id, "--vram", "64"]
    vb.customize ["modifyvm", :id, "--spec-ctrl", "on"]
    vb.customize ["modifyvm", :id, "--clipboard-mode", "bidirectional"]



  end

  config.vm.hostname = "prcpp-desktop"
  config.vm.synced_folder "../ansible/", "/vagrant/ansible"

  # remove not yet supported ansible ppa
  config.vm.provision "shell",
    inline: "rm -f /etc/apt/sources.list.d/ansible-ansible-focal.list"

  config.vm.provision "ansible_local" do |ansible|
    ansible.install_mode = "pip"
    ansible.playbook = "/vagrant/ansible/playbook-desktop.yml"
    ansible.galaxy_role_file = "/vagrant/ansible/requirements.yml"
  end

end
