# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.box_version = "20190905.0.0"



  config.ssh.forward_agent = true
  config.ssh.forward_x11 = true

  config.vm.provider "virtualbox" do |vb|
    vb.name = "prcpp-headless"
    vb.memory = "4096"
    vb.cpus = 2
    vb.customize ["modifyvm", :id, "--vram", "64"]
    vb.customize ["modifyvm", :id, "--spec-ctrl", "on"]

  end

  config.vm.hostname = "prcpp-headless"
  config.vm.synced_folder "../ansible/", "/vagrant/ansible"

  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "/vagrant/ansible/playbook-headless.yml"
    ansible.galaxy_role_file = "/vagrant/ansible/requirements.yml"
  end

end
